.TH "C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/CAcquisition.h" 3 "Wed Mar 17 2021" "Version 1" "PRD COPROD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/CAcquisition.h \- Aquisition des differentes sources de donnees\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'CChantier\&.h'\fP
.br
\fC#include 'COperation\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCAcquisition\fP"
.br
.RI "Classe Aqcuisition\&. "
.in -1c
.SH "Detailed Description"
.PP 
Aquisition des differentes sources de donnees\&. 


.PP
\fBAuthor\fP
.RS 4
Yohan Nouet 
.RE
.PP
\fBVersion\fP
.RS 4
1 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PRD COPROD from the source code\&.
