.TH "C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/CAcquisition.cpp" 3 "Wed Mar 17 2021" "Version 1" "PRD COPROD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/CAcquisition.cpp \- Aquisition des differentes sources de donnees\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CAcquisition\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'CChantier\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <xlnt/xlnt\&.hpp>\fP
.br
\fC#include 'rapidcsv\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Aquisition des differentes sources de donnees\&. 


.PP
\fBAuthor\fP
.RS 4
Yohan Nouet 
.RE
.PP
\fBVersion\fP
.RS 4
1 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PRD COPROD from the source code\&.
