.TH "C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/CInput.h" 3 "Wed Mar 17 2021" "Version 1" "PRD COPROD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/CInput.h \- Elements permettant de fournir les donnees d'entrees a un modele de résolution\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCInput\fP"
.br
.RI "Classe Input\&. "
.in -1c
.SH "Detailed Description"
.PP 
Elements permettant de fournir les donnees d'entrees a un modele de résolution\&. 


.PP
\fBAuthor\fP
.RS 4
Yohan Nouet 
.RE
.PP
\fBVersion\fP
.RS 4
1 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PRD COPROD from the source code\&.
