.TH "C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/CInput.cpp" 3 "Wed Mar 17 2021" "Version 1" "PRD COPROD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/CInput.cpp \- Elements permettant de fournir les donnees d'entrees a un modele de resolution\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CInput\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Elements permettant de fournir les donnees d'entrees a un modele de resolution\&. 


.PP
\fBAuthor\fP
.RS 4
Yohan Nouet 
.RE
.PP
\fBVersion\fP
.RS 4
1 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PRD COPROD from the source code\&.
