.TH "C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/CJeuDonnees.h" 3 "Wed Mar 17 2021" "Version 1" "PRD COPROD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/CJeuDonnees.h \- Elements permettant d instancier des jeux de donnees pour resoudre des instances avec le solveur\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CInput\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCJeuDonnees\fP"
.br
.RI "Classe JeuDonnees\&. "
.in -1c
.SH "Detailed Description"
.PP 
Elements permettant d instancier des jeux de donnees pour resoudre des instances avec le solveur\&. 


.PP
\fBAuthor\fP
.RS 4
Yohan Nouet 
.RE
.PP
\fBVersion\fP
.RS 4
1 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PRD COPROD from the source code\&.
