.TH "CJeuDonnees" 3 "Wed Mar 17 2021" "Version 1" "PRD COPROD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CJeuDonnees \- Classe JeuDonnees\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CJeuDonnees\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCInput\fP \fBversion1\fP ()"
.br
.RI "Generation du jeu de donnee v1\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classe JeuDonnees\&. 

La classe permet de creer des jeux de donnes a l aide de methodes statiques retournant une instance \fBCInput\fP 
.SH "Member Function Documentation"
.PP 
.SS "\fBCInput\fP CJeuDonnees::version1 ()\fC [static]\fP"

.PP
Generation du jeu de donnee v1\&. Methode statique qui permet d'obtenir un jeu de donnee predefini (vesrsion simple)\&.
.PP
\fBReturns\fP
.RS 4
le jeu de donnees 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PRD COPROD from the source code\&.
