.TH "C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/COperation.cpp" 3 "Wed Mar 17 2021" "Version 1" "PRD COPROD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/COperation.cpp \- manipulation d'une operation de maintenance  

.SH SYNOPSIS
.br
.PP
\fC#include 'COperation\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (std::ostream &out, \fBCOperation\fP &obj)"
.br
.RI "Surcharge <<\&. "
.in -1c
.SH "Detailed Description"
.PP 
manipulation d'une operation de maintenance 


.PP
\fBAuthor\fP
.RS 4
Yohan Nouet 
.RE
.PP
\fBVersion\fP
.RS 4
1 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "ostream& operator<< (std::ostream & out, \fBCOperation\fP & obj)"

.PP
Surcharge <<\&. Methode qui permet de surcharger l'utilisation de l'operateur << pour afficher directement le contenu de l'objet\&.
.PP
Ex : std::cout << monOperation; 
.SH "Author"
.PP 
Generated automatically by Doxygen for PRD COPROD from the source code\&.
