.TH "C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/main.cpp" 3 "Wed Mar 17 2021" "Version 1" "PRD COPROD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <Windows\&.h>\fP
.br
\fC#include <ilcplex/ilocplex\&.h>\fP
.br
\fC#include 'Tuto\&.h'\fP
.br
\fC#include 'PLNE\&.h'\fP
.br
\fC#include 'CChantier\&.h'\fP
.br
\fC#include 'CAcquisition\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'CJeuDonnees\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for PRD COPROD from the source code\&.
