.TH "C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/PLNE.h" 3 "Wed Mar 17 2021" "Version 1" "PRD COPROD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/PLNE.h \- Elements permettant de resoudre un probleme d'optimisation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <ilcplex/ilocplex\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'COperation\&.h'\fP
.br
\fC#include 'CInput\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPLNE\fP"
.br
.RI "Classe \fBPLNE\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Elements permettant de resoudre un probleme d'optimisation\&. 


.PP
\fBAuthor\fP
.RS 4
Yohan Nouet 
.RE
.PP
\fBVersion\fP
.RS 4
1 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PRD COPROD from the source code\&.
