.TH "rapidcsv::no_converter" 3 "Wed Mar 17 2021" "Version 1" "PRD COPROD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rapidcsv::no_converter \- Exception thrown when attempting to access \fBDocument\fP data in a datatype which is not supported by the \fBConverter\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rapidcsv\&.h>\fP
.PP
Inherits std::exception\&.
.SH "Detailed Description"
.PP 
Exception thrown when attempting to access \fBDocument\fP data in a datatype which is not supported by the \fBConverter\fP class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for PRD COPROD from the source code\&.
