.TH "C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/rapidcsv.h" 3 "Wed Mar 17 2021" "Version 1" "PRD COPROD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/nouet/Documents/Cours/5A/Dev PRD/PrdCoprod/PrdCoprod/rapidcsv.h
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <typeinfo>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrapidcsv::ConverterParams\fP"
.br
.RI "Datastructure holding parameters controlling how invalid numbers (including empty strings) should be handled\&. "
.ti -1c
.RI "class \fBrapidcsv::no_converter\fP"
.br
.RI "Exception thrown when attempting to access \fBDocument\fP data in a datatype which is not supported by the \fBConverter\fP class\&. "
.ti -1c
.RI "class \fBrapidcsv::Converter< T >\fP"
.br
.RI "Class providing conversion to/from numerical datatypes and strings\&. Only intended for rapidcsv internal usage, but exposed externally to allow specialization for custom datatype conversions\&. "
.ti -1c
.RI "struct \fBrapidcsv::LabelParams\fP"
.br
.RI "Datastructure holding parameters controlling which row and column should be treated as labels\&. "
.ti -1c
.RI "struct \fBrapidcsv::SeparatorParams\fP"
.br
.RI "Datastructure holding parameters controlling how the CSV data fields are separated\&. "
.ti -1c
.RI "class \fBrapidcsv::Document\fP"
.br
.RI "Class representing a CSV document\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrapidcsv\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename T > using \fBrapidcsv::ConvFunc\fP = std::function< void(const std::string &pStr, T &pVal)>"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PRD COPROD from the source code\&.
