.TH "Tuto" 3 "Wed Mar 17 2021" "Version 1" "PRD COPROD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tuto
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Tuto\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBbasic\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Tuto::basic ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for PRD COPROD from the source code\&.
